apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-chat
  namespace: atharva-app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atharva-chat-api
  updatePolicy:
    updateMode: "Off"
