apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: atharva
  namespace: argocd
spec:
  description: Atharva Dental Clinic - LLMOps Bootcamp
  sourceRepos:
    - https://github.com/gd-1234/atharva-dental-assistant
  destinations:
    - namespace: atharva-ml
      server: https://kubernetes.default.svc
    - namespace: atharva-app
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: keda
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
